---
- name: add yum repo
  yum:
    name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
- name: enable repo
  command: percona-release enable-only tools release
  args:
    creates: /etc/yum.repos.d/percona-tools-release.repo
- name: install XtraBackup
  yum:
    name: percona-xtrabackup-{{ xtrabackup_version }}
